language: ruby
rvm:
- 2.0.0
- 2.1.0
before_deploy: git fetch --unshallow
deploy:
  provider: heroku
  api_key:
    secure: e12xuG0WJI+QsyzkKIO0uyYh7pyHNBmLa7OF8DjDLbTaNtZ/gSES6JvVvtark3rgeg9h+dSR3y+xESwVQhi9iFiOs687Wo1jNzk+J7oeqaYTJKzXxPyUgWmdS7xWguD4Sd9PqEzxh0RKo3L7IxF6ULfJxdlgzgSNmLRBXg0C0hU=
  app: bluesourcestaging
  on:
    branch: staging
    rvm: 2.0.0
  buildpack: https://github.com/Orasi/heroku-buildpack-ruby.git
