#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:   &development_defaults
  key:         1234567890ABCDEF1234567890ABCDEF
  iv:          1234567890ABCDEF
  cipher_name: aes-128-cbc
  encoding:    :base64strict

test:
  <<: *development_defaults
  
staging:
  <<: *development_defaults

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAy8gYmJlxeMODhI1RXE4+NuWUiudDfg8R2TQiAF+MWv89ryfP
    yWS/3eVkhE9k5j0/HceVSrgRLkMfGz5uF62uYY8R9sMQRn0FfCNYzkxkL02qdpJv
    +hHkjdXgmnsoEZP0xiFxcBHN/xaJHBicGk15SON6h6TMx5XYJhCEtHWt61G/gDO2
    XmatjgGRq/Emz5crD98be9wPvJgd9oBCQKpJztNdKbSCMqNsyytpBk6Zs6opA/Ol
    3NY6KDLcHf3EqHsFxPCQKIn841yBy39fyQTWhXMuy8vRyRO9NnY33fplXTYhotTO
    gXaUAcc4lX1KJzMn3KosMZsfjgVPZ4XsQ65tEwIDAQABAoIBAApesVm6nTqfAGdT
    ZauD08ipYCi9YgLdM3RRIdXRBuxuhq4OIZXHCbh5/uZ4v9KzlS2nxWIbAczP35pc
    T+/mh7QxOqHLBV4A6LGLfu5olsSNeDo2c3pPRMku9BIIaF6Un+UhOIuSbGApvmpu
    misAfEaIROj4Ku+RIYG2X3prbqFF3XDRAWssSSa0spK/sClbVUKZsqv6y+SumMCs
    S7E2RjSg9n0ey6g90YjPA2fKYiFX4uDHP+CQ0lMAdJWNqqGHPrVNEqDeNWRvUiMW
    AGu8uJzwZayoS+5Mc0edCP36H2LbcXU+50so4z474hTUD6rUuxQk59olmOzdHtxr
    jHlNJzkCgYEA5aQtLG4vS69pwyUlopL/jm1dPEJieP0c3jVNapaqxRs/rWauO3aq
    FMmANDE8asGrCXDcOzAYasQdcTKtmu2iKDQm2qFmfW1oB2xWvGLvSzSnjQ69xqTH
    MJ7agT3vUV4X+2NBN8TH9NQh9i7KX1gN67Lg2rjGZctMWGgBbkrFEZ0CgYEA4ywN
    vIKzQCv69hntTG1zkDRbjAonYwz5Gs/HlBMqAyKjVkBauy3GZCnZjdBnoAlBC2l6
    FPI73HQ4c+ZN7DqWhnnaXyz0zo13UAt6WbpH33jw5A5spTvCQdJOhX8uNQFvCC6B
    +BDgLcrEUtmtRowtwzJO4j2JVxYorJMZQ6Ud0m8CgYEA18o+6NFhgC2FpOrzQqH/
    o0cBpe57ulWfGu/bn52VO0MvwzIJ57bKfF4dKu5ZZ7g1kNmNGdFIIIvJXuXQXRWQ
    m1bma+ve814rs04K81vEoVcJW3POwSt2QioECg65JCzXPFM4pb80ZswwXbX6VT3Z
    VvLweJfJVz6Cr1CMh6ebJ8ECgYEAjSUe98RBORraV7QuMzFB/xP42V6psCosUBNP
    DlqF3OLVl05u0SOUw0EZUbpt2ApH5p5HYuJKfSOcu64ZNjAEvFLTchUNmZRd0FcB
    UuShqWCMUzX/HP6vKJRRgzJM9FQKt4ul5wodL3ZvWoay2UVZXZFRX9IaFgjHhsny
    hYv+pnMCgYBezs8AKHA2SKDCLn3JEfsquO3as5dCdKHhwPP6FNDisFbIV0e8xIda
    jXwNs8x2TiNTMEyHc8hHslcEJgeGNYBCFE1aQfYgV2PHM9mTjDhntGAwu/S0570V
    8os5+iOkqb6Jj0Sq/9ZLFrTiNbVUGpWLh8mt2dAAaM+1qYqo0MgBAg==
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename: /etc/rails/keys/manager_portal_release.key
      iv_filename:  /etc/rails/keys/manager_portal_release.iv
      cipher_name:  aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:     :base64strict
      version:      1

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAo/Xt9W5Bg7e9zcY117XIJz6VjRCGxc3fEsAIyCKdox7vigfz
    YMjhU4Ry2i6iSk+/QQZ1TfGzglFMVe6CFvkve7PoYFtRhShjqoByPkFLE0E4lA91
    wFI+vxeyXoV/o7Nr+DeoncAnMSdEmmaWfG4l8w1gJOyor2P/+BAYrwK6txrxgIXd
    WITjg+gG7T/uVmK9mzQyjneAT4YD6jGoGn8q1nCCrYMyf+eT5lywMkL+JNSh9h1l
    gbMRJB9VZRdrELETL5+0ha3Xsr+IX4v14gOV/C1m4TcdCJnzkKIQsqSb9QgHh9CH
    8LNxaaolRlH0JqnPLYW+UybYKIfkBqngXyNh6QIDAQABAoIBAEwluodC1pB69F6u
    EHGHTlbTnRcvtrgFHfYSU8HHOdj5VBySBrlLckKcf87O27aRhOyJOE+j0k/SvBYo
    uCg9QI0+B81AfALQuEEGeIhrQJfHsaQp7fENAXE0azW04IvBl4JnLxtck5cjepwO
    yxMtANj5vE5Jzynt0oJ9z0jwhpDk5xVzjH/u6wsZKSEAZmtj0wctJJLeqdHvfQTv
    8C2cPgcpS2JCq4WZr6ViSVHHfTIezHLlUYn9aYBeaJiYFlTorcVCxUTLABvkDkER
    OfjG+kMc0Kme0Aq/Ohp2EQYkCPRLMl/kUL0yCfULSBRWTQFDBeNzh8Dx1e/gJAlm
    Xw6rj4ECgYEA1OFg/qL3aQvzHKFr5GhWwWjSdP67UdIq1ndyH7mgI8ONPJIJkTmT
    Gjp5yhR7MmIKpGA15zGZd0oZbDK3A1dNkY0OrcpWIRDoFasfrChb0d7BEruAEZN9
    igCRb6KJY5+abgLLyNSuRh2ThqKu9X8vB5jb8emPvf3Awu3P5cixfpECgYEAxSvi
    opwfjJonQqz6Jy84XZGdtApSG2RfmhzF7rD9NWwh2qmzmWITVNkpjV+N/RXP7qaI
    zyex4hGaPo7ho1LAXU8pCfcZZgPzzuC8TLx7Vv4EOtxaFTWU8vKYoulbcbnxy5ak
    TYRgA1hblDRgDwAHR/FODTSUkCo0i9wDOuV8CdkCgYAEqUaxbKoUL8HL/7DYGHzF
    0WDCVQ2O9hYgCg+CqFLcVZzTFbOF7YfODDe8eARWjxUCkmS7wjdFCGdUGiwts4ys
    QjVvEr4eDTu3tb6Ey4FvL/x0R4y/VcZq7iZBFoMBnm4IOKFzrUx/logza35/O6Cw
    /uTaAC44j8TXv9NMib9xMQKBgCBc7K0uHQuR/eG2zLSDzqelEBKOIx314q9EC8T6
    7gTHw+LFOgJyE6Q4pNZcmcyxuNh+IzSFWnA13XBpOWX6XjKynJTTJysUeP866g1a
    XpBPz1ft9SdIDTO3WBBdZzIKiEKXbk5+7Nd/uEBiPGYZ5hgL5njKaZwkIU3Xhfwz
    0KE5AoGBAIlcgEIZxUdxazG7vNz2HU4RPcls6iyy3FF/hu2jIjHeMqNaOmXlcHf8
    orpTH2PNjGylvhNaKlEjcZrZ8scv/oud0heDWq7jXFisc+rakaNp+MYUMwhEywHe
    QLy4u6mNNizHmUTR3meZhwm1iUzzaJ30Ax/cb65fntLI/qKdWwyW
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename: /etc/rails/keys/manager_portal_production.key
      iv_filename:  /etc/rails/keys/manager_portal_production.iv
      cipher_name:  aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:     :base64strict
      version:      1
